const $=s=>document.querySelector(s),app=$('#app');
const pairs={food:[['うどん','そば'],['カレー','シチュー'],['アイス','かき氷'],['りんご','梨'],['ピザ','お好み焼き'],['コーヒー','紅茶'],['寿司','おにぎり'],['チョコ','キャラメル'],['ケーキ','ドーナツ'],['ラーメン','つけ麺'],['餃子','焼売'],['パンケーキ','クレープ'],['焼肉','しゃぶしゃぶ'],['ぶどう','さくらんぼ'],['ポップコーン','ポテトチップス']],life:[['お風呂','シャワー'],['電車','バス'],['映画館','劇場'],['図書館','本屋'],['海','プール'],['動物園','水族館'],['夏','冬'],['自転車','バイク'],['鉛筆','ボールペン'],['リュック','トートバッグ'],['遊園地','公園'],['猫','犬'],['学校','塾'],['サッカー','バスケットボール'],['キャンプ','ピクニック'],['エレベーター','エスカレーター'],['傘','レインコート'],['旅行','帰省'],['スマホ','タブレット'],['誕生日','クリスマス']]};
let cfg={count:5,names:Array(12).fill(''),minutes:3,category:'all'},g=null,tick=null,seen=new Set();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const random=n=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%n};
function render(html){app.innerHTML=html;$('#home').hidden=!g;window.scrollTo(0,0)}
function setup(){clearInterval(tick);g=null;render(`<div class="layout"><section class="intro"><div class="eyebrow">PASS THE TABLET</div><h1>そのお題、<br>みんなと同じ？</h1><p class="sub">少しだけ違うお題を持つ「ウルフ」を、<br>会話の中から見つけよう。</p><svg class="wolf" viewBox="0 0 200 180" aria-hidden="true"><circle cx="100" cy="92" r="80" fill="#e8ecdf"/><path d="M42 25L78 55H122L158 25L149 125L100 160L51 125Z" fill="#293832"/><path d="M51 87L100 109L149 87L135 129L100 153L65 129Z" fill="#edba70"/><path d="M70 80L85 85M115 85L130 80" stroke="#fff" stroke-width="6"/><path d="M89 111H111L100 122Z" fill="#293832"/></svg><details class="rules"><summary>はじめて遊ぶ方へ</summary><p>① タブレットを回して、自分のお題だけ確認。<br>② お題の言葉を直接言わず、特徴や思い出を話そう。<br>③ 違うお題を持っていそうな人に秘密投票。<br>④ 最多票の人がウルフなら市民の勝ち！</p><p>ウルフは1人。本人にも役割はわかりません。同票は決選投票、再び同票なら引き分けです。</p></details></section><section class="panel"><h2>みんなで準備</h2><div class="row"><b>プレイヤー</b><div class="stepper"><button id="minus" aria-label="人数を減らす">−</button><span>${cfg.count}人</span><button id="plus" aria-label="人数を増やす">＋</button></div></div><div class="names">${Array.from({length:cfg.count},(_,i)=>`<input aria-label="プレイヤー${i+1}の名前" data-name="${i}" maxlength="20" placeholder="プレイヤー${i+1}" value="${esc(cfg.names[i])}">`).join('')}</div><label class="field"><span>お題のジャンル</span><select id="category"><option value="all">おまかせミックス</option><option value="food">食べもの</option><option value="life">身近なもの</option></select></label><label class="field"><span>話し合いの時間</span><select id="minutes">${[1,2,3,4,5,7,10].map(n=>`<option value="${n}">${n}分</option>`).join('')}</select></label><p class="small sub">ウルフは1人 ／ 3〜12人で遊べます</p><p id="error" class="error" role="alert"></p><button class="primary" id="start">お題を配る →</button></section></div>`);$('#category').value=cfg.category;$('#minutes').value=cfg.minutes;app.querySelectorAll('[data-name]').forEach(el=>el.oninput=()=>cfg.names[Number(el.dataset.name)]=el.value);$('#minus').onclick=()=>{cfg.count=Math.max(3,cfg.count-1);setup()};$('#plus').onclick=()=>{cfg.count=Math.min(12,cfg.count+1);setup()};$('#category').onchange=e=>cfg.category=e.target.value;$('#minutes').onchange=e=>cfg.minutes=Number(e.target.value);$('#start').onclick=start}
function start(){const names=cfg.names.slice(0,cfg.count).map((n,i)=>n.trim()||`プレイヤー${i+1}`);if(new Set(names).size!==names.length){$('#error').textContent='名前が重ならないようにしてください。';return}let pool=cfg.category==='all'?Object.values(pairs).flat():pairs[cfg.category];let available=pool.filter(p=>!seen.has(p.join('/')));if(!available.length){seen.clear();available=pool}const pair=[...available[random(available.length)]];seen.add(pair.join('/'));if(random(2))pair.reverse();g={names,pair,wolf:random(names.length),index:0,phase:'reveal',votes:[],runoff:false,candidates:names.map((_,i)=>i),remaining:cfg.minutes*60,running:false};pass()}
function frame(badge,title,body){render(`<section class="center"><span class="badge">${badge}</span><h1>${title}</h1><div class="panel">${body}</div></section>`)}
function pass(){g.selected=null;const voting=g.phase==='vote';frame(voting?(g.runoff?'決選投票':'秘密投票'):'お題の確認',`${esc(g.names[g.index])}さんへ`, `<p class="sub">タブレットを渡してください。<br>ほかの人は画面を見ないでね。</p><div class="progress"><i style="width:${g.index/g.names.length*100}%"></i></div><p class="small sub">${g.index+1} / ${g.names.length}人目</p><button class="primary" id="open">${voting?'自分の投票画面を開く':'自分のお題を見る'}</button>`);$('#open').onclick=voting?ballot:reveal}
function reveal(){frame('あなたのお題',`${esc(g.names[g.index])}さん`, `<div class="secret"><div class="word">${esc(g.pair[g.index===g.wolf?1:0])}</div></div><p class="sub">この言葉を覚えてください。<br>自分がウルフかは、まだ秘密です。</p><button class="primary" id="hide">お題を隠して${g.index===g.names.length-1?'話し合いへ':'次の人へ'}</button>`);$('#hide').onclick=()=>{g.index++;g.index<g.names.length?pass():ready()}}
function ready(){frame('全員の確認が完了','会話から、見つけよう。',`<p>お題の言葉を直接言うのはNG。<br>「いつ使う？」「どんなところが好き？」<br>ヒントを出し合って話してみよう。</p><p class="sub">話し合い ${cfg.minutes}分</p><button class="primary" id="talk">話し合いを始める</button>`);$('#talk').onclick=()=>{g.phase='talk';g.running=true;g.deadline=Date.now()+g.remaining*1000;discussion();tick=setInterval(updateTimer,250)}}
function timeText(){return `${Math.floor(g.remaining/60).toString().padStart(2,'0')}:${(g.remaining%60).toString().padStart(2,'0')}`}
function updateTimer(){if(!g||g.phase!=='talk'||!g.running)return;g.remaining=Math.max(0,Math.ceil((g.deadline-Date.now())/1000));$('#clock').textContent=timeText();if(!g.remaining){g.running=false;$('#pause').hidden=true;$('#timer-note').textContent='時間です！ 怪しい人を決めて投票しよう。';$('#clock').setAttribute('aria-label','話し合い終了')}}
function discussion(){frame('話し合い','違うお題は、誰の手に？',`<div id="clock" class="timer" role="timer">${timeText()}</div><p id="timer-note" class="sub">言葉そのものは言わずに、会話を楽しもう。</p><button class="secondary" id="pause">${g.running?'一時停止':'再開'}</button><button class="primary" id="vote">話し合いを終えて投票へ →</button>`);$('#pause').onclick=()=>{if(g.running)updateTimer();g.running=!g.running;if(g.running)g.deadline=Date.now()+g.remaining*1000;$('#pause').textContent=g.running?'一時停止':'再開'};$('#vote').onclick=()=>{clearInterval(tick);g.phase='vote';g.index=0;g.votes=[];pass()}}
function ballot(){frame(g.runoff?'決選投票':'秘密投票',`${esc(g.names[g.index])}さんの投票`, `<p class="sub">ウルフだと思う人を1人選んでください。<br>${g.runoff?'同票だった人から選びます。':'自分には投票できません。'}</p><div class="choices">${g.candidates.filter(i=>i!==g.index).map(i=>`<button class="choice" data-vote="${i}">${esc(g.names[i])}</button>`).join('')}</div><button class="primary" id="confirm" disabled>投票を確定して隠す</button>`);app.querySelectorAll('[data-vote]').forEach(el=>el.onclick=()=>{g.selected=Number(el.dataset.vote);app.querySelectorAll('[data-vote]').forEach(b=>b.classList.toggle('selected',b===el));$('#confirm').disabled=false});$('#confirm').onclick=()=>{if(g.selected===null)return;g.votes.push(g.selected);g.index++;g.index<g.names.length?pass():tally()}}
function tally(){const counts=g.names.map((_,i)=>g.votes.filter(v=>v===i).length),max=Math.max(...counts),leaders=counts.flatMap((n,i)=>n===max?[i]:[]);g.counts=counts;g.leaders=leaders;if(leaders.length>1&&!g.runoff){frame('票が分かれました','決選投票へ',`<p>${leaders.map(i=>esc(g.names[i])).join('、')}さんが<br>それぞれ${max}票で同票です。</p><p class="sub">この人たちの中から、もう一度投票します。</p><button class="primary" id="runoff">決選投票を始める</button>`);$('#runoff').onclick=()=>{g.runoff=true;g.candidates=leaders;g.index=0;g.votes=[];pass()}}else{frame('投票が完了','みんなで画面を見よう',`<p class="sub">投票が終わりました。<br>タブレットを真ん中に置いてください。</p><button class="primary" id="result">結果を発表する</button>`);$('#result').onclick=result}}
function result(){g.phase='result';const draw=g.leaders.length>1,win=!draw&&g.leaders[0]===g.wolf;frame('RESULT',draw?'引き分け！':win?'市民チームの勝ち！':'ウルフの勝ち！',`<p>${draw?'決選投票も同票でした。':win?'見事、違うお題の人を見つけました。':'ウルフは最後まで隠れきりました。'}</p><div class="secret"><span class="small">ウルフは</span><div class="word" style="font-size:32px">${esc(g.names[g.wolf])}さん</div></div><div class="row"><div>市民のお題<br><b>${esc(g.pair[0])}</b></div><div>ウルフのお題<br><b>${esc(g.pair[1])}</b></div></div><div class="result-list">${g.names.map((n,i)=>`<div class="result-item ${i===g.wolf?'w':''}"><span>${esc(n)} ${i===g.wolf?'🐺':''}</span><b>${g.counts[i]}票</b></div>`).join('')}</div><button class="primary" id="again">同じメンバーでもう一度</button><button class="secondary" id="settings">人数・設定を変える</button>`);$('#again').onclick=start;$('#settings').onclick=setup}
$('#home').onclick=()=>$('#quit').showModal();$('#quit-no').onclick=()=>$('#quit').close();$('#quit-yes').onclick=()=>{$('#quit').close();setup()};document.addEventListener('visibilitychange',()=>{if(document.hidden&&g&&g.phase==='reveal'){pass()}else if(!document.hidden&&g&&g.phase==='talk')updateTimer()});setup();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_game_progress',description:'Read the current game phase and player count without exposing secret words, roles or votes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw new Error('No arguments accepted');return {phase:g?.phase||'setup',playerCount:g?.names.length||cfg.count}}})).catch(()=>{})}catch{}}

