let audioContext=null,soundOn=true,audioNodes=new Set();
try{soundOn=localStorage.getItem('wolf-sound')!=='off'}catch{}
const soundButton=document.createElement('button');soundButton.id='sound';
function soundLabel(){soundButton.textContent=soundOn?'♪ 音 ON':'♪ 音 OFF';soundButton.setAttribute('aria-pressed',String(soundOn));soundButton.setAttribute('aria-label',soundOn?'効果音をオフにする':'効果音をオンにする')}
const actions=document.createElement('div');actions.className='header-actions';$('#home').before(actions);actions.append(soundButton,$('#home'));soundLabel();
function unlockAudio(){if(!soundOn)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume().catch(()=>{})}catch{}}
function tone(freq,duration=.15,delay=0,type='sine',volume=.07,end=freq){if(!soundOn||!audioContext||audioContext.state!=='running')return;try{const osc=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(freq,now);osc.frequency.exponentialRampToValueAtTime(Math.max(1,end),now+duration);gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.012);gain.gain.exponentialRampToValueAtTime(.001,now+duration);osc.connect(gain);gain.connect(audioContext.destination);audioNodes.add(osc);osc.onended=()=>{audioNodes.delete(osc);gain.disconnect()};osc.start(now);osc.stop(now+duration+.02)}catch{}}
function stopSounds(){for(const node of audioNodes){try{node.stop()}catch{}}audioNodes.clear()}
function sound(kind){if(kind==='tap')tone(540,.07,0,'sine',.035,380);if(kind==='secret'){tone(330,.4,0,'sine',.06);tone(495,.45,.1,'sine',.045)}if(kind==='beat'){tone(65,.18,0,'sine',.13,40);tone(58,.15,.23,'sine',.08,35)}if(kind==='bell'){[523,659,784].forEach((f,i)=>tone(f,.7,i*.16,'sine',.06))}if(kind==='wolf'){tone(150,.9,0,'triangle',.09,65);tone(220,1.1,.05,'sine',.05,110)}if(kind==='win'){[392,494,587,784].forEach((f,i)=>tone(f,.55,i*.13,'triangle',.045))}}
soundButton.onclick=()=>{soundOn=!soundOn;if(!soundOn)stopSounds();else{unlockAudio();sound('secret')}soundLabel();try{localStorage.setItem('wolf-sound',soundOn?'on':'off')}catch{}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||b===soundButton)return;unlockAudio();sound(b.id==='open'?'secret':'tap')},true);
const originalRender=render;render=function(html){stopSounds();document.body.classList.remove('suspense','reveal-wolf');originalRender(html)};
const originalSetup=setup;setup=function(){originalSetup();$('.eyebrow').textContent='月夜の秘密会議';$('.tag').textContent='この輪の中に、ウルフがいる。';$('.wolf').outerHTML='<img class="wolf" src="wolf.svg" alt="月明かりに浮かぶ狼">'};
const originalTimer=updateTimer;updateTimer=function(){const before=g?.remaining;originalTimer();if(g?.phase==='talk'){ $('#clock')?.classList.toggle('urgent',g.remaining<=10);if(before>0&&g.remaining===0)sound('bell')}};
const originalTally=tally;tally=function(){originalTally();if($('#result'))$('#result').onclick=beginReveal};
function beginReveal(){g.phase='suspense';const draw=g.leaders.length>1;frame('最後の審判',draw?'決選投票も、同票。':'みんなが選んだのは…',`<div class="moon-seal">☾</div><div class="accused">${g.leaders.map(i=>esc(g.names[i])+'さん').join('・')}</div><p class="sub">${draw?'今夜、ウルフを見抜くことはできなかった。<br>隠れていた正体を確かめよう。':'その人は、市民か。それともウルフか。'}</p><button class="primary" id="unmask">${draw?'隠れたウルフの正体を開く':'正体を開く'}</button>`);document.body.classList.add('suspense');sound('beat');$('#unmask').onclick=()=>showRole(draw)}
function showRole(draw){const target=draw?g.wolf:g.leaders[0],isWolf=target===g.wolf;g.phase='role';frame('正体が明らかに',`${esc(g.names[target])}さんは…`, `<div class="role-enter"><div class="moon-seal">${isWolf?'🐺':'✦'}</div><div class="reveal-role">${isWolf?'ワードウルフ':'市民'}</div><p class="sub">${draw?'ウルフは、最後まで夜に紛れていた。':isWolf?'少し違う言葉を持っていたのは、この人。':'同じ言葉を持つ仲間だった。ウルフはまだ別の場所に。'}</p></div><button class="primary" id="outcome">勝敗と全員のお題を見る →</button>`);document.body.classList.toggle('reveal-wolf',isWolf);sound(isWolf?'wolf':'secret');$('#outcome').onclick=result}
const originalResult=result;result=function(){originalResult();sound(g.leaders.length>1?'bell':g.leaders[0]===g.wolf?'win':'wolf')};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopSounds()});
setup();
